config/routes.rb
Rails.application.routes.draw do
  resources :veggies

  resources :chickens

  resources :appetizers

  resources :soups

  resources :specials

  resources :menus

  devise_for :members
  resources :users
  resources :searches
  resources :posts
  root to: "posts#index"

end

app/models/appetizer.rb
class Appetizer < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, presence: true
  validates_presence_of :body, presence: true
  validates_uniqueness_of :title
  has_attached_file :image
  has_attached_file :resource
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/soup.rb
class Soup < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/special.rb
class Special < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/veggie.rb
class Veggie < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/controllers/appetizers_controller.rb
class AppetizersController < ApplicationController
  before_action :set_appetizer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @appetizers = Appetizer.all
    respond_with(@appetizers)
  end

  def show
    respond_with(@appetizer)
  end

  def new
    @appetizer = Appetizer.new
    respond_with(@appetizer)
  end

  def edit
  end

  def create
    @appetizer = Appetizer.new(appetizer_params)
    @appetizer.save
    respond_with(@appetizer)
  end

  def update
    @appetizer.update(appetizer_params)
    respond_with(@appetizer)
  end

  def destroy
    @appetizer.destroy
    respond_with(@appetizer)
  end

  private
    def set_appetizer
      @appetizer = Appetizer.find(params[:id])
    end

    def appetizer_params
      params.require(:appetizer).permit(:name, :price, :description)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @menus = Menu.all
    respond_with(@menus)
  end

  def show
    respond_with(@menu)
  end

  def new
    @menu = Menu.new
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    respond_with(@menu)
  end

  def update
    @menu.update(menu_params)
    respond_with(@menu)
  end

  def destroy
    @menu.destroy
    respond_with(@menu)
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params[:menu]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_member, only: [:new, :create, :destroy, :edit, :update]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @posts = Post.all
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image, :resource)
    end
end

app/helpers/appetizers_helper.rb
module AppetizersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/veggies_helper.rb
module VeggiesHelper
end

app/views/appetizers/_form.html.erb
<%= simple_form_for(@appetizer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appetizers/edit.html.erb
<h1>Editing appetizer</h1>

<%= render 'form' %>

<%= link_to 'Show', @appetizer %> |
<%= link_to 'Back', appetizers_path %>

app/views/appetizers/index.html.erb
<h1>Listing appetizers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appetizers.each do |appetizer| %>
      <tr>
        <td><%= appetizer.name %></td>
        <td><%= appetizer.price %></td>
        <td><%= appetizer.description %></td>
        <td><%= link_to 'Show', appetizer %></td>
        <td><%= link_to 'Edit', edit_appetizer_path(appetizer) %></td>
        <td><%= link_to 'Destroy', appetizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appetizer', new_appetizer_path %>

app/views/appetizers/new.html.erb
<h1>New appetizer</h1>

<%= render 'form' %>

<%= link_to 'Back', appetizers_path %>

app/views/appetizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appetizer.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @appetizer.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appetizer.description %>
</p>

<%= link_to 'Edit', edit_appetizer_path(@appetizer) %> |
<%= link_to 'Back', appetizers_path %>