config/routes.rb
Rails.application.routes.draw do
  resources :veggies

  resources :chickens

  resources :appetizers

  resources :soups

  resources :specials

  resources :menus

  devise_for :members
  resources :users
  resources :searches
  resources :posts
  root to: "posts#index"

end

app/models/appetizer.rb
class Appetizer < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, presence: true
  validates_presence_of :body, presence: true
  validates_uniqueness_of :title
  has_attached_file :image
  has_attached_file :resource
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/soup.rb
class Soup < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/special.rb
class Special < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/veggie.rb
class Veggie < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @menus = Menu.all
    respond_with(@menus)
  end

  def show
    respond_with(@menu)
  end

  def new
    @menu = Menu.new
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    respond_with(@menu)
  end

  def update
    @menu.update(menu_params)
    respond_with(@menu)
  end

  def destroy
    @menu.destroy
    respond_with(@menu)
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params[:menu]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_member, only: [:new, :create, :destroy, :edit, :update]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @posts = Post.all
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image, :resource)
    end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
  before_action :set_soup, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @soups = Soup.all
    respond_with(@soups)
  end

  def show
    respond_with(@soup)
  end

  def new
    @soup = Soup.new
    respond_with(@soup)
  end

  def edit
  end

  def create
    @soup = Soup.new(soup_params)
    @soup.save
    respond_with(@soup)
  end

  def update
    @soup.update(soup_params)
    respond_with(@soup)
  end

  def destroy
    @soup.destroy
    respond_with(@soup)
  end

  private
    def set_soup
      @soup = Soup.find(params[:id])
    end

    def soup_params
      params.require(:soup).permit(:name, :size, :price)
    end
end

app/helpers/appetizers_helper.rb
module AppetizersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/veggies_helper.rb
module VeggiesHelper
end

app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-item" } do |f| %>

    <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :body, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:body]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            posts_path, :class => 'btn btn-default' %>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">House of Hunan</h1>
  </div>
</div>
<div class="neighborhood-guides">
  <div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="thumbnail">
              <img src="http://www.dineouthere.com/images/sushi-town-17.jpg">
              <p><strong>Fried Rice</strong>. It has some fried stuff element to it, you'll like it</p>
            </div>
          </div>
            <div class="col-md-3">
            <div class="thumbnail">
              <img src="http://www.tulsapeople.com/in%20the%20raw5689.jpg">
              <center><p>I think it's a <strong>Candy Roll</strong><p></center>
            </div>
          </div>
         <div class="col-md-3">
            <div class="thumbnail">
              <img src="http://www.dineouthere.com/images/sushi-town-17.jpg">
              <p>We even semi-cook our nigiri, just to be safe</p>
            </div>
        </div>
         <div class="col-md-3">
            <div class="thumbnail">
                <img src="http://cookingontheweekends.com/wp-content/uploads/2012/05/April13-Shrimp-Ceviche31.jpg">
                <p>Ceviche on a martini glass, can't get more original than this!</p>
            </div>
        </div>
    </div>
  </div>
</div>
<div class="col-md-12">
<h2 class="text-center">Why us?</h2>
</div>
    <div class="container">
     <div class="row">
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://i2.ytimg.com/vi/f0j3-nd3kJo/hqdefault.jpg">
          </div>
          <h3>Executive Chef</h3>
          <p>Leo Bandana? The Big Kahuna? Magic Leo?</p>
          <p><a href="#">See him works out</a></p>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://i2.ytimg.com/vi/f0j3-nd3kJo/hqdefault.jpg">
          </div>
          <h3>Multiple locations</h3>
          <p>It's a food truck! Our location changes everyday. </p>
          <p><a href="#">Learn more</a></p>
        </div>
        <div class="col-md-4">
          <div class="thumbnail">
            <img src="http://a4.urbancdn.com/w/s/Su/M3DInxMUimhaQ0-640m.jpg">
          </div>
        </div>
        <div class="col-md-4">
          <h3>Trust our brand</h3>
          <p>It's essentially In the Raw without tipping your server :) Unless you really want to </p>
          <p><a href="#">Learn more</a></p>
        </div>
      </div>
    </div>
  </div>
  <hr/>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <center><p>built by &#0153;Seasalt Labs</p></center>
        </div>
      </div>
    </div>
  </footer>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1 class="text-center"><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>


<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @post.body %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/soups/_form.html.erb
<%= simple_form_for(@soup) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :size %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/soups/edit.html.erb
<h1>Editing soup</h1>

<%= render 'form' %>

<%= link_to 'Show', @soup %> |
<%= link_to 'Back', soups_path %>

app/views/soups/index.html.erb
<h1>Listing soups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @soups.each do |soup| %>
      <tr>
        <td><%= soup.name %></td>
        <td><%= soup.size %></td>
        <td><%= soup.price %></td>
        <td><%= link_to 'Show', soup %></td>
        <td><%= link_to 'Edit', edit_soup_path(soup) %></td>
        <td><%= link_to 'Destroy', soup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Soup', new_soup_path %>

app/views/soups/new.html.erb
<h1>New soup</h1>

<%= render 'form' %>

<%= link_to 'Back', soups_path %>

app/views/soups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @soup.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @soup.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @soup.price %>
</p>

<%= link_to 'Edit', edit_soup_path(@soup) %> |
<%= link_to 'Back', soups_path %>