config/routes.rb
Rails.application.routes.draw do
  resources :veggies

  resources :chickens

  resources :appetizers

  resources :soups

  resources :specials

  resources :menus

  devise_for :members
  resources :users
  resources :searches
  resources :posts
  root to: "posts#index"

end

app/models/appetizer.rb
class Appetizer < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/chicken.rb
class Chicken < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, presence: true
  validates_presence_of :body, presence: true
  validates_uniqueness_of :title
  has_attached_file :image
  has_attached_file :resource
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/soup.rb
class Soup < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/special.rb
class Special < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/veggie.rb
class Veggie < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @menus = Menu.all
    respond_with(@menus)
  end

  def show
    respond_with(@menu)
  end

  def new
    @menu = Menu.new
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.save
    respond_with(@menu)
  end

  def update
    @menu.update(menu_params)
    respond_with(@menu)
  end

  def destroy
    @menu.destroy
    respond_with(@menu)
  end

  private
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def menu_params
      params[:menu]
    end
end

app/controllers/veggies_controller.rb
class VeggiesController < ApplicationController
  before_action :set_veggy, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @veggies = Veggie.all
    respond_with(@veggies)
  end

  def show
    respond_with(@veggy)
  end

  def new
    @veggy = Veggie.new
    respond_with(@veggy)
  end

  def edit
  end

  def create
    @veggy = Veggie.new(veggie_params)
    @veggy.save
    respond_with(@veggy)
  end

  def update
    @veggy.update(veggie_params)
    respond_with(@veggy)
  end

  def destroy
    @veggy.destroy
    respond_with(@veggy)
  end

  private
    def set_veggy
      @veggy = Veggie.find(params[:id])
    end

    def veggy_params
      params.require(:veggy).permit(:name, :price, :description)
    end
end

app/helpers/appetizers_helper.rb
module AppetizersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chickens_helper.rb
module ChickensHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/veggies_helper.rb
module VeggiesHelper
end

app/views/veggies/_form.html.erb
<%= simple_form_for(@veggy) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/veggies/edit.html.erb
<h1>Editing veggy</h1>

<%= render 'form' %>

<%= link_to 'Show', @veggy %> |
<%= link_to 'Back', veggies_path %>

app/views/veggies/index.html.erb
<h1>Listing veggies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veggies.each do |veggy| %>
      <tr>
        <td><%= veggy.name %></td>
        <td><%= veggy.price %></td>
        <td><%= veggy.description %></td>
        <td><%= link_to 'Show', veggy %></td>
        <td><%= link_to 'Edit', edit_veggy_path(veggy) %></td>
        <td><%= link_to 'Destroy', veggy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veggie', new_veggy_path %>

app/views/veggies/new.html.erb
<h1>New veggy</h1>

<%= render 'form' %>

<%= link_to 'Back', veggies_path %>

app/views/veggies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @veggy.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @veggy.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @veggy.description %>
</p>

<%= link_to 'Edit', edit_veggy_path(@veggy) %> |
<%= link_to 'Back', veggies_path %>